//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torneio.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TorneioEntities : DbContext
    {
        public TorneioEntities()
            : base("name=TorneioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jogadores> Jogadores { get; set; }
        public virtual DbSet<Partidas> Partidas { get; set; }
        public virtual DbSet<Times> Times { get; set; }
        public virtual DbSet<Torneios> Torneios { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Escalacoes> Escalacoes { get; set; }
    }
}
