//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torneio.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escalacoes
    {
        public int IDTime { get; set; }
        public int IDPartida { get; set; }
        public int IDJogador { get; set; }
        public bool Titular { get; set; }
        public string Posicao { get; set; }
    
        public virtual Jogadores Jogadores { get; set; }
        public virtual Partidas Partidas { get; set; }
        public virtual Times Times { get; set; }
    }
}
