//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torneio.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Torneios()
        {
            this.Partidas = new HashSet<Partidas>();
            this.Torneios_Times = new HashSet<Torneios_Times>();
            this.usuarios_torneios = new HashSet<usuarios_torneios>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Premiacao { get; set; }
        public int Ano { get; set; }
        public string Realizador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partidas> Partidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneios_Times> Torneios_Times { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios_torneios> usuarios_torneios { get; set; }
    }
}
