//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torneio.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneios_Times
    {
        public int ID { get; set; }
        public int IDTorneio { get; set; }
        public int IDTime { get; set; }
    
        public virtual Times Times { get; set; }
        public virtual Torneios Torneios { get; set; }
    }
}
